### ISSUE TITLE
use // to force a new line

### ISSUE THREAD

**Issue by beniza** [Bridgeconn/usfm-grammar#61]
I just saw the following line in a discussion. Because it was shared by an expert in usfm, I think it is a valid case. 

> to force line breaks--for which // is the appropriate SFM.

Does your grammar support this?

**Comment by beniza** [comment]
Looks like it doesn't

**Input**
![image](https://user-images.githubusercontent.com/4908971/81268735-f3868f00-9065-11ea-87ab-0bafc48edd54.png)

**output**
![image](https://user-images.githubusercontent.com/4908971/81268971-482a0a00-9066-11ea-8d66-76b65e5b4fd0.png)

**Comment by joelthe1** [comment]
Do you have a suggestions on how this should be handled? We could just replace these with `\n` but that wouldn't be very interoperable.

**Comment by joelthe1** [comment]
I think for now replacing `//` with `\n` might be good enough.

**Comment by kavitharaju** [comment]
We can do that.
There are two more similar components in [USFM spec](https://ubsicap.github.io/usfm/characters/index.html#spacing-and-breaks), `~` and `\pb`. I assume we are to leave them as it is, and change only `\\`.

**Comment by joelthe1** [comment]
Actually, reading the [link](https://ubsicap.github.io/usfm/characters/index.html#spacing-and-breaks), it says:
> Discretionary (optional) line break. 

So now I am not sure if we should always convert `//` to `\n`. And looking at `~`, makes me think that that is a more obvious change.

**Comment by kavitharaju** [comment]
Our current approach is to treat `//` and `~` as part of text and `\pb` in similar way as paragraph markers. This way, it is preserved in converted JSON and would be intact if we re-create USFM from it.

**Comment by joelthe1** [comment]
So from talking/thinking more about it the plan is to **keep** `//` as is in the text since blindly converting it to a newline character is actually incorrect since it is optional (based on the screen where the text is being rendered). This should be documented.

We plan to, however, change `~` into [no-break space](https://ubsicap.github.io/usfm/characters/index.html#spacing-and-breaks) from USFM->JSON and vice-verse.

**Comment by beniza** [comment]
I'd ask the following questions before any implementations are done
What does an optional line break mean? What are the use cases? What
conditions can trigger the *optional* line break.

Jeff should be able to throw some lights.

/b

**Comment by cmahte** [comment]
\\ represents breakpoints for those lines where they appear.

I do a complex replace...

(1) any paragraph with \\ present has all nontag spaces transformed to
nbsp,  then
(2) any \\ are transformed into spaces.
(z) This only works effectively if hyphenation is turned off for the
paragraph style in the composer. But theoretically, anyone utilizing \\
instead of \q2 ... \q3 is doing so early in the translation process, so the
hyphenation won't be defined either.

**Comment by cmahte** [comment]
The related chunk... This is a beanshell macro... all \ are doubled, and
must be doubled again to be text existing in searches.  otherwise you
should be able to make out the logic:

// ==== No break spaces =====================================
// -- double slashes become spaces
// -- after other spaces become no break in those paragraphs
SearchAndReplace.setSearchString("(^\\+)//(.+[^/]$)");
SearchAndReplace.setReplaceString("$1//$2//");
SearchAndReplace.replaceAll(view);
SearchAndReplace.setSearchString(" (?=[^\\n]+//)");
SearchAndReplace.setReplaceString("~");
SearchAndReplace.replaceAll(view);
SearchAndReplace.setSearchString("//(?=[^\\n]+//)");
SearchAndReplace.setReplaceString(" ");
SearchAndReplace.replaceAll(view);
SearchAndReplace.setSearchString("(\\\\[^\\n]+?)~");
SearchAndReplace.setReplaceString("$1 ");
SearchAndReplace.replaceAll(view);
SearchAndReplace.setSearchString("//");
SearchAndReplace.setReplaceString("<pHyphenation:0>");
SearchAndReplace.replaceAll(view);

**Comment by klassenjm** [comment]
`//` is intended as optional, as Joel is highlighting. It's not widely used, but some projects do add it to things like longer section headings to indicate where they would prefer to break the text if it does not fit on one line. Some may add it to poetry or lists (but I don't have an example on hand) to indicate preferred breaks. It is not intended to say "always break". USX has `<optbreak/>`, and this is what PT exports for these.

`\pb` is awkward, since it is very print centric. What does it really mean in other publication formats? It's a paragraph type in USFM. USX simply provides for having an empty paragraph like `<para style="pb"/>`

It would be good to preserve `//` and `\pb` somehow -- to not lose content. I'm not sure what you would do in JSON.

I would agree to transform to ~ to no-break space U+00A0

Jeff

**Comment by joelthe1** [comment]
Fixed and merged via #94.
