### ISSUE TITLE
How do you generate usfm.ohm.js file?

### ISSUE THREAD

**Issue by sakhmedbayev** [Bridgeconn/usfm-grammar#65]
I wonder how do you generate `usfm.ohm.js` file? I understand that it has as its value (`exports.contents = `) the content of the `usfm.ohm` file.

can anything like the following to work as well?

```
const contents = fs.readFileSync(
  '../grammar/usfm.ohm',
);
```

instead of this:

```
const { contents } = require("../grammar/usfm.ohm.js");
```
Please let me know

**Comment by joelthe1** [comment]
Thanks for the suggestion. I believe this could work and may be better. @kavitharaju do you agree?

**Comment by sakhmedbayev** [comment]
Here is a better version. It will work with yarn link as well:

```
const contents = fs.readFileSync(
  path.resolve(__dirname, '../grammar/usfm.ohm'),
);
```

**Comment by joelthe1** [comment]
The main reason for us to do this has been to accommodate usage of `usfm-grammar` on the browser, we have been avoiding the use of the `fs` library. And having a check to figure out the running context does not preclude having this generated usfm.ohm.js file. I don't see value in having this file _and_ having logic that auto-generates it. In case you think there is a way to completely avoid having this file please let us know. But otherwise I think it makes sense to continue doing this.

**Comment by sakhmedbayev** [comment]
OK
